### ISSUE TITLE
Missing MetaData files

### ISSUE THREAD

**Issue by Philipp-Weigand** [McDonnell-Lab/MALDI-UNISA-ML#1]
Dear Author,

I am trying to reproduce your results, but I do not have access to all files that are necessary to run your code.
For example, the `PrepareData_EC.ipynb` script expects the excel file `../MetaData/TMA 16-006 map_nodata.xlsx`.
I can't find any `xlsx` files in the PRIDE repository, which you provided. I assume, the `dat` files contain some of the data, which I need to run your scripts. However, I don't know how to read or convert them. Which software was used, to create these `dat` files?

I would be very grateful if you could help me to run your script!

Kind regards,
Philipp

**Comment by McDonnell-Lab** [comment]
Hi Philipp,

Unfortunately I have no knowledge of whether the data can be obtained publicly, or if not whether you can be given access. I suggest you contact Professor Peter Hoffman: see here for details - https://people.unisa.edu.au/peter.hoffmann

Cheers,

Mark McDonnell
